name: build
on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build:
    name: Build and upload to riffraff
    runs-on: ubuntu-latest
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.GU_RIFF_RAFF_ROLE_ARN }}
          aws-region: eu-west-1

      - name: Configure private infra config credentials
        uses: guardian/actions-read-private-repos@v0.1.0
        with:
          private-ssh-keys: ${{ secrets.PRIVATE_INFRASTRUCTURE_CONFIG_DEPLOY_KEY }}

      - name: Setup node for CDK
        uses: actions/setup-node@v4
        with:
          cache: 'npm'
          cache-dependency-path: 'cdk/package-lock.json'
          node-version-file: '.nvmrc'

      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'
          cache: 'sbt'

      - name: Build
        run: |
          ./scripts/build.sh

      - name: Upload to Riff-Raff
        uses: guardian/actions-riff-raff@v2
        with:
          projectName: 'Hiring & Onboarding Tools::CV Redact'
          configPath: cdk/cdk.out/riff-raff.yaml
          contentDirectories: |
            cdk.out:
              - cdk/cdk.out
            cv-redact-tool:
              - target/cv-redact-tool.deb
