name: build
on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build:
    name: Build and upload to riffraff
    runs-on: ubuntu-latest
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.GU_RIFF_RAFF_ROLE_ARN }}
          aws-region: eu-west-1

      - name: Setup node for CDK
        uses: actions/setup-node@v2 # This is required by cdk
        with:
          cache: 'npm'
          cache-dependency-path: 'cdk/package-lock.json'
          node-version-file: '.nvmrc'

      - name: Setup java
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt' 
 
      - name: Build
        run: |
          ./script/build.sh
          
      - name: Upload to Riff-Raff
        uses: guardian/actions-riff-raff@v2
        with:
          app: cv-redact-tool
          config: |
            stacks:
              - deploy
            regions:
              - eu-west-1
            allowedStages:
              - PROD
            deployments:
              cv-redact-tool:
                type: autoscaling
                actions: [deploy]
                sources:
                  - build
                parameters:
                  bucket: cv-redact-tool-dist
