name: build
on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build:
    name: Build and upload to riffraff
    runs-on: ubuntu-latest
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read
      pull-requests: write # required since guardian/actions-riff-raff@v3
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure private infra config credentials
        uses: guardian/actions-read-private-repos@v0.1.0
        with:
          private-ssh-keys: ${{ secrets.PRIVATE_INFRASTRUCTURE_CONFIG_DEPLOY_KEY }}

      - name: Setup bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: './cdk/.bun-version'

      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'
          cache: 'sbt'

      - name: Setup SBT
        uses: sbt/setup-sbt@v1

      - name: Build
        run: |
          ./scripts/build.sh

      - name: Upload to Riff-Raff
        uses: guardian/actions-riff-raff@v4
        with:
          roleArn: ${{ secrets.GU_RIFF_RAFF_ROLE_ARN }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          projectName: 'Hiring & Onboarding Tools::CV Redact'
          configPath: cdk/cdk.out/riff-raff.yaml
          contentDirectories: |
            cdk.out:
              - cdk/cdk.out
            cv-redact-tool:
              - target/cv-redact-tool.deb
